import openClawLobster from './assets/openclaw-lobster.svg';
import claudeCodeImage from './assets/claude-code.jpg';
import mrMeeseeksImage from './assets/mr-meeseeks.png';

const clamp = (value, min, max) => Math.min(max, Math.max(min, value));

function buildSystem(overrides = {}) {
  const displayMode = clamp(overrides.displayMode ?? 0, 0, 1);
  return {
    displayMode,
    defense: clamp(overrides.defense ?? 0, 0, 1),
    phase: clamp(overrides.phase ?? 0.5, 0, 1),
    horizon: clamp(overrides.horizon ?? 0.44, 0.08, 0.92),
    bandCurve: clamp(overrides.bandCurve ?? 0.6, 0, 1),
    beamTilt: clamp(overrides.beamTilt ?? 0.58, 0, 1),
    lattice: clamp(overrides.lattice ?? 0.7, 0, 1),
    density: clamp(overrides.density ?? 0.6, 0, 1),
    aperture: clamp(overrides.aperture ?? 0.52, 0, 1),
    warningBias: clamp(overrides.warningBias ?? 0.76, 0, 1),
    reticleBias: clamp(overrides.reticleBias ?? 0.34, 0, 1),
    scan: clamp(overrides.scan ?? 0.66, 0, 1),
    notch: clamp(overrides.notch ?? 0.46, 0, 1),
    skew: clamp(overrides.skew ?? 0.18, 0, 1),
    contour: clamp(overrides.contour ?? 0.7, 0, 1),
    interference: clamp(overrides.interference ?? 0.58, 0, 1),
    pulse: clamp(overrides.pulse ?? 0.48, 0, 1),
    gate: clamp(overrides.gate ?? 0.54, 0, 1),
    sensorField: clamp(overrides.sensorField ?? Math.max(0, (displayMode - 0.68) / 0.32), 0, 1),
    bloom: clamp(overrides.bloom ?? Math.max(0, (displayMode - 0.52) / 0.48), 0, 1),
    ruler: clamp(overrides.ruler ?? Math.max(0, (displayMode - 0.62) / 0.38), 0, 1),
    diagnostics: clamp(overrides.diagnostics ?? 0, 0, 1),
    waist: clamp(overrides.waist ?? 0.48, 0, 1),
  };
}

const scene = (base, haze, toxic, magenta, warning, light, system) => ({
  base,
  haze,
  toxic,
  magenta,
  warning,
  light,
  system: buildSystem(system),
});

export const slides = [
  {
    id: 'opening',
    kicker: '',
    title: 'Productionsing openclaw',
    layout: 'hero',
    scene: scene(
      [2, 2, 4],
      [12, 6, 4],
      [255, 160, 40],
      [255, 140, 50],
      [255, 180, 60],
      { x: 0.88, y: 0.12, radius: 0.84, strength: 1.22 },
      {
        displayMode: 0.16,
        defense: 0.14,
        phase: 0.08,
        horizon: 0.78,
        bandCurve: 0.32,
        beamTilt: 0.38,
        lattice: 0.86,
        density: 0.74,
        aperture: 0.62,
        warningBias: 0.86,
        reticleBias: 0.22,
        scan: 0.64,
        notch: 0.28,
        skew: 0.12,
        contour: 0.8,
        interference: 0.48,
        pulse: 0.34,
        gate: 0.62,
      },
    ),
    lede: '',
    chips: [],
    facts: [],
    note: '',
  },
  {
    id: 'will',
    kicker: '',
    title: 'Will @ twodot.ai',
    layout: 'steps',
    scene: scene(
      [3, 2, 3],
      [14, 8, 4],
      [240, 150, 35],
      [255, 130, 40],
      [255, 170, 55],
      { x: 0.74, y: 0.08, radius: 0.92, strength: 1.28 },
      {
        displayMode: 0.18,
        defense: 0.2,
        phase: 0.18,
        horizon: 0.54,
        bandCurve: 0.44,
        beamTilt: 0.54,
        lattice: 0.7,
        density: 0.62,
        aperture: 0.58,
        warningBias: 0.8,
        reticleBias: 0.18,
        scan: 0.72,
        notch: 0.42,
        skew: 0.18,
        contour: 0.68,
        interference: 0.62,
        pulse: 0.5,
        gate: 0.56,
        sensorField: 0.26,
        bloom: 0.38,
        ruler: 0.18,
        diagnostics: 0.2,
        waist: 0.46,
      },
    ),
    steps: [
      { title: 'twodot.ai', body: 'Platform for hosting business agents that complete tasks' },
      { title: 'Tech lead', body: 'Since the start', accent: 'focus' },
      { title: 'What\'s next', body: 'Moving into assistants on the platform' },
    ],
    tags: [],
  },
  {
    id: 'what-is-openclaw',
    kicker: '',
    title: 'What is OpenClaw?',
    layout: 'hero',
    scene: scene(
      [2, 3, 8],
      [8, 12, 18],
      [40, 220, 200],
      [60, 180, 160],
      [255, 180, 60],
      { x: 0.58, y: 0.22, radius: 0.78, strength: 1.18 },
      {
        displayMode: 0.08,
        defense: 0.08,
        phase: 0.32,
        horizon: 0.5,
        bandCurve: 0.4,
        beamTilt: 0.62,
        lattice: 0.78,
        density: 0.56,
        aperture: 0.48,
        warningBias: 0.72,
        reticleBias: 0.32,
        scan: 0.58,
        notch: 0.48,
        skew: 0.16,
        contour: 0.56,
        interference: 0.52,
        pulse: 0.42,
        gate: 0.44,
      },
    ),
    lede: 'Open-source AI agent framework. Built mid-2024, exploded in early 2025. Founder acqui-hired by OpenAI.',
    chips: ['Open source', 'Agent framework', 'Stream of consciousness'],
    facts: [
      { value: '30k+', label: 'GitHub stars' },
      { value: '2024', label: 'Created' },
      { value: 'OpenAI', label: 'Acqui-hire' },
    ],
    note: '',
    visual: {
      src: openClawLobster,
      alt: 'OpenClaw logo',
      fit: 'contain',
      badge: '',
      caption: '',
    },
  },
  {
    id: 'devs-vs-normies',
    kicker: '',
    title: 'Developers vs normies',
    layout: 'diagram',
    diagramId: 'devs-vs-normies',
    scene: scene(
      [2, 4, 10],
      [6, 14, 20],
      [50, 210, 190],
      [70, 170, 150],
      [255, 190, 70],
      { x: 0.46, y: 0.08, radius: 0.98, strength: 1.34 },
      {
        displayMode: 0.24,
        defense: 0.12,
        phase: 0.44,
        horizon: 0.76,
        bandCurve: 0.58,
        beamTilt: 0.6,
        lattice: 0.88,
        density: 0.72,
        aperture: 0.52,
        warningBias: 0.78,
        reticleBias: 0.42,
        scan: 0.7,
        notch: 0.5,
        skew: 0.1,
        contour: 0.74,
        interference: 0.4,
        pulse: 0.4,
        gate: 0.68,
      },
    ),
    steps: [
      { title: 'Normies', body: 'Think it\'s cool, use it daily' },
      { title: 'Devs', body: 'See security holes, stop looking further', accent: 'focus' },
    ],
  },
  {
    id: 'one-and-done-vs-stream',
    kicker: '',
    title: 'The Meeseeks approach',
    titleSize: 'compact',
    layout: 'hero',
    scene: scene(
      [3, 4, 12],
      [8, 8, 20],
      [180, 150, 80],
      [200, 160, 100],
      [255, 160, 60],
      { x: 0.8, y: 0.12, radius: 0.82, strength: 1.2 },
      {
        displayMode: 0.86,
        defense: 0.1,
        phase: 0.28,
        horizon: 0.6,
        bandCurve: 0.4,
        beamTilt: 0.6,
        lattice: 0.7,
        density: 0.48,
        aperture: 0.5,
        warningBias: 0.8,
        reticleBias: 0.3,
        scan: 0.56,
        notch: 0.4,
        skew: 0.18,
        contour: 0.52,
        interference: 0.42,
        pulse: 0.36,
        gate: 0.52,
        sensorField: 0.82,
        bloom: 0.38,
        ruler: 0.9,
        waist: 0.58,
      },
    ),
    lede: 'Spawn, do task, die.',
    chips: [],
    facts: [],
    note: '',
    visual: {
      src: mrMeeseeksImage,
      alt: 'Mr. Meeseeks - spawn, do task, die',
      fit: 'contain',
      compact: true,
      badge: '',
      caption: '',
    },
    panels: [
      { title: 'Everyone else', body: 'One-and-done' },
      { title: 'OpenClaw', body: 'One long living stream', accent: 'focus' },
    ],
  },
  {
    id: 'meeseeks-table',
    kicker: '',
    title: 'Who does a Meeseeks?',
    titleSize: 'compact',
    layout: 'compare',
    scene: scene(
      [3, 4, 12],
      [8, 8, 20],
      [180, 150, 80],
      [200, 160, 100],
      [255, 160, 60],
      { x: 0.8, y: 0.12, radius: 0.82, strength: 1.2 },
      {
        displayMode: 0.86,
        defense: 0.1,
        phase: 0.28,
        horizon: 0.6,
        bandCurve: 0.4,
        beamTilt: 0.6,
        lattice: 0.7,
        density: 0.48,
        aperture: 0.5,
        warningBias: 0.8,
        reticleBias: 0.3,
        scan: 0.56,
        notch: 0.4,
        skew: 0.18,
        contour: 0.52,
        interference: 0.42,
        pulse: 0.36,
        gate: 0.52,
        sensorField: 0.82,
        bloom: 0.38,
        ruler: 0.9,
        waist: 0.58,
      },
    ),
    compare: {
      left: {
        label: 'Product',
        title: '',
        body: '',
      },
      right: {
        label: 'Approach',
        title: '',
        body: '',
      },
      rows: [
        { topic: 'ChatGPT', left: 'Spawn, do task, die', right: 'Meeseeks' },
        { topic: 'Claude Code', left: 'Spawn, do task, die', right: 'Meeseeks' },
        { topic: 'Gemini', left: 'Spawn, do task, die', right: 'Meeseeks' },
        { topic: 'Perplexity', left: 'Spawn, do task, die', right: 'Meeseeks' },
        { topic: 'Cursor', left: 'Spawn, do task, die', right: 'Meeseeks' },
        { topic: 'OpenClaw', left: 'Long living stream of consciousness', right: 'Continuous' },
      ],
    },
    note: '',
  },
  {
    id: 'lanes',
    kicker: '',
    title: 'Lane System',
    titleSize: 'compact',
    layout: 'diagram',
    diagramId: 'lanes',
    scene: scene(
      [3, 3, 10],
      [10, 10, 22],
      [170, 140, 75],
      [190, 150, 90],
      [255, 170, 65],
      { x: 0.54, y: 0.08, radius: 0.98, strength: 1.38 },
      {
        displayMode: 0.56,
        defense: 0.96,
        phase: 0.48,
        horizon: 0.64,
        bandCurve: 0.62,
        beamTilt: 0.58,
        lattice: 0.9,
        density: 0.76,
        aperture: 0.56,
        warningBias: 0.78,
        reticleBias: 0.36,
        scan: 0.74,
        notch: 0.58,
        skew: 0.14,
        contour: 0.86,
        interference: 0.5,
        pulse: 0.52,
        gate: 0.74,
        sensorField: 0.14,
        bloom: 0.46,
        ruler: 0.2,
        diagnostics: 0.34,
        waist: 0.44,
      },
    ),
    steps: [
      { title: 'Two-layer queue', body: 'Session lane first, then global lane — serialises per-session' },
      { title: 'No starvation', body: 'Subagents and cron can\'t block user requests', accent: 'focus' },
      { title: 'Deadlock-proof', body: 'Nested lane catches inner ops that would self-block cron' },
      { title: 'Session store bridge', body: 'Lanes don\'t share data — results flow through transcripts', accent: 'cool' },
    ],
  },
  {
    id: 'heartbeat',
    kicker: '',
    title: 'Heartbeat',
    titleSize: 'compact',
    layout: 'diagram',
    diagramId: 'heartbeat',
    scene: scene(
      [2, 2, 4],
      [10, 6, 3],
      [255, 155, 38],
      [250, 135, 45],
      [255, 175, 58],
      { x: 0.86, y: 0.12, radius: 0.86, strength: 1.24 },
      {
        displayMode: 0.88,
        defense: 0.24,
        phase: 0.18,
        horizon: 0.58,
        bandCurve: 0.46,
        beamTilt: 0.64,
        lattice: 0.68,
        density: 0.52,
        aperture: 0.6,
        warningBias: 0.84,
        reticleBias: 0.34,
        scan: 0.64,
        notch: 0.46,
        skew: 0.2,
        contour: 0.64,
        interference: 0.56,
        pulse: 0.44,
        gate: 0.5,
        sensorField: 0.52,
        bloom: 0.56,
        ruler: 0.46,
        diagnostics: 0.42,
        waist: 0.58,
      },
    ),
    steps: [
      { title: 'Every 30 min', body: 'Periodic check for outstanding work + notifications' },
      { title: 'Main session', body: 'Runs with full conversation history', accent: 'focus' },
      { title: 'Smart skip', body: 'Returns HEARTBEAT_OK if nothing pending' },
      { title: 'Configurable', body: 'HEARTBEAT.md defines intervals, hours, delivery', accent: 'cool' },
    ],
  },
  {
    id: 'core-docs',
    kicker: '',
    title: 'Core Docs',
    titleSize: 'compact',
    layout: 'diagram',
    diagramId: 'core-docs',
    scene: scene(
      [2, 3, 9],
      [6, 10, 16],
      [45, 215, 195],
      [55, 175, 155],
      [255, 185, 65],
      { x: 0.66, y: 0.1, radius: 0.94, strength: 1.32 },
      {
        displayMode: 0.82,
        defense: 0.16,
        phase: 0.26,
        horizon: 0.62,
        bandCurve: 0.48,
        beamTilt: 0.6,
        lattice: 0.74,
        density: 0.58,
        aperture: 0.54,
        warningBias: 0.8,
        reticleBias: 0.24,
        scan: 0.68,
        notch: 0.54,
        skew: 0.18,
        contour: 0.72,
        interference: 0.48,
        pulse: 0.48,
        gate: 0.58,
      },
    ),
    steps: [
      { title: 'SOUL.md', body: 'Who the agent IS — personality, values, constraints' },
      { title: 'AGENTS.md', body: 'Behavioral guidelines and role definitions', accent: 'focus' },
      { title: 'HEARTBEAT.md', body: 'Periodic task schedules and check-in config' },
      { title: 'MEMORY.md', body: 'Curated long-term context the agent learns', accent: 'cool' },
      { title: 'TOOLS.md', body: 'Available tool specs and capability declarations' },
    ],
  },
  {
    id: 'prompt-assembly',
    kicker: '',
    title: 'Prompt Construction',
    titleSize: 'compact',
    layout: 'diagram',
    diagramId: 'prompt-assembly',
    scene: scene(
      [2, 4, 12],
      [8, 12, 20],
      [50, 200, 180],
      [60, 170, 150],
      [255, 180, 65],
      { x: 0.58, y: 0.14, radius: 0.9, strength: 1.28 },
      {
        displayMode: 0.74,
        defense: 0.14,
        phase: 0.3,
        horizon: 0.66,
        bandCurve: 0.5,
        beamTilt: 0.58,
        lattice: 0.76,
        density: 0.6,
        aperture: 0.52,
        warningBias: 0.78,
        reticleBias: 0.28,
        scan: 0.66,
        notch: 0.5,
        skew: 0.16,
        contour: 0.7,
        interference: 0.46,
        pulse: 0.44,
        gate: 0.56,
        sensorField: 0.38,
        bloom: 0.42,
        ruler: 0.32,
        diagnostics: 0.28,
        waist: 0.5,
      },
    ),
    steps: [
      { title: 'Bootstrap files', body: 'SOUL, AGENTS, IDENTITY, TOOLS, MEMORY' },
      { title: 'Assembler', body: 'Merges all sections into one system prompt', accent: 'focus' },
      { title: 'Session history', body: 'Full transcript, compacted on overflow' },
      { title: 'Token budget', body: '20K/file, 150K total — auto-prune', accent: 'cool' },
    ],
  },
  {
    id: 'cron',
    kicker: '',
    title: 'Cron System',
    titleSize: 'compact',
    layout: 'diagram',
    diagramId: 'cron',
    scene: scene(
      [2, 3, 8],
      [8, 18, 16],
      [45, 225, 185],
      [230, 55, 38],
      [255, 105, 32],
      { x: 0.74, y: 0.1, radius: 0.96, strength: 1.32 },
      {
        displayMode: 0.3,
        defense: 0.18,
        phase: 0.14,
        horizon: 0.68,
        bandCurve: 0.52,
        beamTilt: 0.62,
        lattice: 0.8,
        density: 0.64,
        aperture: 0.58,
        warningBias: 0.82,
        reticleBias: 0.28,
        scan: 0.72,
        notch: 0.48,
        skew: 0.16,
        contour: 0.76,
        interference: 0.54,
        pulse: 0.5,
        gate: 0.64,
      },
    ),
    steps: [
      { title: '3 schedule types', body: 'at (one-shot), every (interval), cron (expression)' },
      { title: 'Session options', body: 'Main, isolated cron:<jobId>, or custom', accent: 'focus' },
      { title: 'Delivery', body: 'announce, webhook, or none' },
      { title: 'Reliability', body: 'Persisted, retry with backoff, auto-stagger', accent: 'cool' },
    ],
  },
  {
    id: 'tasks',
    kicker: '',
    title: 'Task Management',
    titleSize: 'compact',
    layout: 'diagram',
    diagramId: 'tasks',
    scene: scene(
      [3, 3, 10],
      [10, 10, 22],
      [170, 140, 75],
      [190, 150, 90],
      [255, 170, 65],
      { x: 0.54, y: 0.08, radius: 0.98, strength: 1.38 },
      {
        displayMode: 0.56,
        defense: 0.96,
        phase: 0.48,
        horizon: 0.64,
        bandCurve: 0.62,
        beamTilt: 0.58,
        lattice: 0.9,
        density: 0.76,
        aperture: 0.56,
        warningBias: 0.78,
        reticleBias: 0.36,
        scan: 0.74,
        notch: 0.58,
        skew: 0.14,
        contour: 0.86,
        interference: 0.5,
        pulse: 0.52,
        gate: 0.74,
        sensorField: 0.14,
        bloom: 0.46,
        ruler: 0.2,
        diagnostics: 0.34,
        waist: 0.44,
      },
    ),
    steps: [
      { title: 'Tracks all work', body: 'ACP runs, subagents, cron, CLI ops' },
      { title: 'Lifecycle', body: 'queued → running → succeeded | failed | lost', accent: 'focus' },
      { title: 'SQLite', body: '7-day retention, auto-reconciliation' },
      { title: 'Orchestration', body: 'Managed or mirrored mode', accent: 'cool' },
    ],
  },
  {
    id: 'claude',
    kicker: '',
    title: 'Claude Code: coding-first',
    layout: 'quote',
    scene: scene(
      [2, 2, 6],
      [16, 8, 12],
      [255, 210, 45],
      [210, 65, 250],
      [255, 145, 50],
      { x: 0.84, y: 0.08, radius: 1.08, strength: 1.48 },
      {
        displayMode: 0.54,
        defense: 0.4,
        phase: 0.1,
        horizon: 0.72,
        bandCurve: 0.7,
        beamTilt: 0.66,
        lattice: 0.92,
        density: 0.8,
        aperture: 0.72,
        warningBias: 0.88,
        reticleBias: 0.18,
        scan: 0.8,
        notch: 0.56,
        skew: 0.12,
        contour: 0.9,
        interference: 0.6,
        pulse: 0.66,
        gate: 0.78,
        sensorField: 0.36,
        bloom: 0.5,
        ruler: 0.24,
        diagnostics: 0.22,
        waist: 0.52,
      },
    ),
    quote: 'Reads codebase, makes changes, runs tests, commits.',
    attribution: 'Anthropic',
    context: '',
    visual: {
      src: claudeCodeImage,
      alt: 'Claude Code',
      fit: 'cover',
      badge: '',
      caption: '',
    },
    panels: [
      { title: 'Scope', body: 'Coding-first', accent: 'focus' },
      { title: 'Benchmark', body: 'For coding AI' },
    ],
  },
  {
    id: 'practice',
    kicker: '',
    title: 'How to think about it',
    layout: 'split-note',
    scene: scene(
      [2, 4, 8],
      [10, 22, 20],
      [40, 220, 180],
      [220, 50, 40],
      [255, 100, 30],
      { x: 0.86, y: 0.14, radius: 0.88, strength: 1.16 },
      {
        displayMode: 0.12,
        defense: 0.18,
        phase: 0.16,
        horizon: 0.58,
        bandCurve: 0.48,
        beamTilt: 0.64,
        lattice: 0.72,
        density: 0.52,
        aperture: 0.54,
        warningBias: 0.84,
        reticleBias: 0.28,
        scan: 0.6,
        notch: 0.36,
        skew: 0.14,
        contour: 0.62,
        interference: 0.46,
        pulse: 0.38,
        gate: 0.48,
      },
    ),
    panels: [
      {
        title: 'Good',
        bullets: ['repeatable chores', 'reconciliation', 'multi-step coordination'],
        accent: 'focus',
      },
      {
        title: 'Bad',
        bullets: ['unbounded autonomy', 'destructive actions', 'theater'],
      },
    ],
    note: '',
  },
  {
    id: 'takeaways',
    kicker: '',
    title: 'Takeaways',
    layout: 'grid',
    scene: scene(
      [3, 3, 10],
      [10, 10, 22],
      [170, 140, 75],
      [190, 150, 90],
      [255, 170, 65],
      { x: 0.54, y: 0.08, radius: 0.98, strength: 1.38 },
      {
        displayMode: 0.56,
        defense: 0.96,
        phase: 0.48,
        horizon: 0.64,
        bandCurve: 0.62,
        beamTilt: 0.58,
        lattice: 0.9,
        density: 0.76,
        aperture: 0.56,
        warningBias: 0.78,
        reticleBias: 0.36,
        scan: 0.74,
        notch: 0.58,
        skew: 0.14,
        contour: 0.86,
        interference: 0.5,
        pulse: 0.52,
        gate: 0.74,
        sensorField: 0.14,
        bloom: 0.46,
        ruler: 0.2,
        diagnostics: 0.34,
        waist: 0.44,
      },
    ),
    cards: [
      { title: 'Mainstreaming', body: '' },
      { title: 'Structural comparison', body: '', accent: 'focus' },
      { title: 'Tech is early', body: '' },
      { title: 'Ops is next', body: '', accent: 'cool' },
      { title: 'Right benchmark', body: '' },
    ],
  },
  {
    id: 'closing',
    kicker: '',
    title: 'What changes',
    layout: 'closing',
    scene: scene(
      [2, 2, 6],
      [16, 8, 12],
      [255, 210, 45],
      [210, 65, 250],
      [255, 145, 50],
      { x: 0.84, y: 0.08, radius: 1.08, strength: 1.48 },
      {
        displayMode: 0.54,
        defense: 0.4,
        phase: 0.1,
        horizon: 0.72,
        bandCurve: 0.7,
        beamTilt: 0.66,
        lattice: 0.92,
        density: 0.8,
        aperture: 0.72,
        warningBias: 0.88,
        reticleBias: 0.18,
        scan: 0.8,
        notch: 0.56,
        skew: 0.12,
        contour: 0.9,
        interference: 0.6,
        pulse: 0.66,
        gate: 0.78,
        sensorField: 0.36,
        bloom: 0.5,
        ruler: 0.24,
        diagnostics: 0.22,
        waist: 0.52,
      },
    ),
    cards: [
      { title: 'Management model', body: 'Direct agents' },
      { title: 'Broader participation', body: '', accent: 'focus' },
      { title: 'Real leverage', body: 'Continuity, control, real systems', accent: 'cool' },
    ],
    closing: '',
  },
];
