const clamp = (value, min, max) => Math.min(max, Math.max(min, value));

function buildSystem(overrides = {}) {
  const displayMode = clamp(overrides.displayMode ?? 0, 0, 1);
  return {
    displayMode,
    defense: clamp(overrides.defense ?? 0, 0, 1),
    phase: clamp(overrides.phase ?? 0.5, 0, 1),
    horizon: clamp(overrides.horizon ?? 0.44, 0.08, 0.92),
    bandCurve: clamp(overrides.bandCurve ?? 0.6, 0, 1),
    beamTilt: clamp(overrides.beamTilt ?? 0.58, 0, 1),
    lattice: clamp(overrides.lattice ?? 0.7, 0, 1),
    density: clamp(overrides.density ?? 0.6, 0, 1),
    aperture: clamp(overrides.aperture ?? 0.52, 0, 1),
    warningBias: clamp(overrides.warningBias ?? 0.76, 0, 1),
    reticleBias: clamp(overrides.reticleBias ?? 0.34, 0, 1),
    scan: clamp(overrides.scan ?? 0.66, 0, 1),
    notch: clamp(overrides.notch ?? 0.46, 0, 1),
    skew: clamp(overrides.skew ?? 0.18, 0, 1),
    contour: clamp(overrides.contour ?? 0.7, 0, 1),
    interference: clamp(overrides.interference ?? 0.58, 0, 1),
    pulse: clamp(overrides.pulse ?? 0.48, 0, 1),
    gate: clamp(overrides.gate ?? 0.54, 0, 1),
    sensorField: clamp(overrides.sensorField ?? Math.max(0, (displayMode - 0.68) / 0.32), 0, 1),
    bloom: clamp(overrides.bloom ?? Math.max(0, (displayMode - 0.52) / 0.48), 0, 1),
    ruler: clamp(overrides.ruler ?? Math.max(0, (displayMode - 0.62) / 0.38), 0, 1),
    diagnostics: clamp(overrides.diagnostics ?? 0, 0, 1),
    waist: clamp(overrides.waist ?? 0.48, 0, 1),
  };
}

const scene = (base, haze, toxic, magenta, warning, light, system) => ({
  base,
  haze,
  toxic,
  magenta,
  warning,
  light,
  system: buildSystem(system),
});

export const slides = [
  {
    id: 'adoption',
    kicker: 'Adoption',
    title: 'Uptake splits for a reason',
    layout: 'trio',
    scene: scene(
      [2, 3, 8],
      [22, 8, 38],
      [122, 255, 76],
      [214, 58, 255],
      [255, 92, 46],
      { x: 0.88, y: 0.12, radius: 0.84, strength: 1.22 },
      {
        displayMode: 0.16,
        defense: 0.14,
        phase: 0.08,
        horizon: 0.78,
        bandCurve: 0.32,
        beamTilt: 0.38,
        lattice: 0.86,
        density: 0.74,
        aperture: 0.62,
        warningBias: 0.86,
        reticleBias: 0.22,
        scan: 0.64,
        notch: 0.28,
        skew: 0.12,
        contour: 0.8,
        interference: 0.48,
        pulse: 0.34,
        gate: 0.62,
      },
    ),
    cards: [
      {
        label: 'Developers',
        title: 'See breakage first',
        bullets: ['rough edges', 'weak guarantees', 'context drift'],
      },
      {
        label: 'Reading',
        title: 'Both reactions are rational',
        body: 'Reliability teams reject early. Workflow teams lean in.',
        accent: 'focus',
      },
      {
        label: 'Operators',
        title: 'Feel leverage first',
        bullets: ['repetitive work', 'messy reconciliation', 'friction-heavy ops'],
        accent: 'cool',
      },
    ],
  },
  {
    id: 'design-signal',
    kicker: 'Design',
    title: 'Safe environments create product signal',
    layout: 'steps',
    scene: scene(
      [2, 3, 8],
      [26, 10, 48],
      [104, 248, 88],
      [232, 74, 255],
      [255, 110, 56],
      { x: 0.74, y: 0.08, radius: 0.92, strength: 1.28 },
      {
        displayMode: 0.18,
        defense: 0.2,
        phase: 0.18,
        horizon: 0.54,
        bandCurve: 0.44,
        beamTilt: 0.54,
        lattice: 0.7,
        density: 0.62,
        aperture: 0.58,
        warningBias: 0.8,
        reticleBias: 0.18,
        scan: 0.72,
        notch: 0.42,
        skew: 0.18,
        contour: 0.68,
        interference: 0.62,
        pulse: 0.5,
        gate: 0.56,
        sensorField: 0.26,
        bloom: 0.38,
        ruler: 0.18,
        diagnostics: 0.2,
        waist: 0.46,
      },
    ),
    steps: [
      { title: 'Rough idea', body: '"This should be automated."' },
      { title: 'Bounded trial', body: 'Test it without production risk.', accent: 'focus' },
      { title: 'Real use', body: 'Operators and clients push on it.' },
      { title: 'Signal', body: 'Failure shows up early.', accent: 'cool' },
    ],
    tags: ['prototype fast', 'bound the risk', 'widen participation', 'learn earlier'],
  },
  {
    id: 'twodot',
    kicker: 'twodot.ai',
    title: 'Operating claws, not demo chats',
    layout: 'split',
    scene: scene(
      [1, 4, 7],
      [18, 16, 28],
      [104, 255, 82],
      [188, 44, 255],
      [255, 118, 48],
      { x: 0.58, y: 0.22, radius: 0.78, strength: 1.18 },
      {
        displayMode: 0.08,
        defense: 0.08,
        phase: 0.32,
        horizon: 0.5,
        bandCurve: 0.4,
        beamTilt: 0.62,
        lattice: 0.78,
        density: 0.56,
        aperture: 0.48,
        warningBias: 0.72,
        reticleBias: 0.32,
        scan: 0.58,
        notch: 0.48,
        skew: 0.16,
        contour: 0.56,
        interference: 0.52,
        pulse: 0.42,
        gate: 0.44,
      },
    ),
    panels: [
      {
        title: 'What we build',
        bullets: ['role-based assistants', 'real permissions and tools', 'hosted for ongoing work'],
      },
      {
        title: 'Why it matters',
        body: 'Work moves through real systems instead of a polished demo.',
        accent: 'focus',
      },
    ],
  },
  {
    id: 'workflow',
    kicker: 'Workflow',
    title: 'Business work is state movement',
    layout: 'steps',
    scene: scene(
      [1, 3, 6],
      [12, 18, 18],
      [88, 250, 92],
      [164, 36, 255],
      [255, 88, 38],
      { x: 0.46, y: 0.08, radius: 0.98, strength: 1.34 },
      {
        displayMode: 0.24,
        defense: 0.12,
        phase: 0.44,
        horizon: 0.76,
        bandCurve: 0.58,
        beamTilt: 0.6,
        lattice: 0.88,
        density: 0.72,
        aperture: 0.52,
        warningBias: 0.78,
        reticleBias: 0.42,
        scan: 0.7,
        notch: 0.5,
        skew: 0.1,
        contour: 0.74,
        interference: 0.4,
        pulse: 0.4,
        gate: 0.68,
      },
    ),
    steps: [
      { title: 'Read CRM' },
      { title: 'Check email' },
      { title: 'Cross-check tracking' },
      { title: 'Resolve mismatches' },
      { title: 'Update systems', accent: 'focus' },
    ],
    note: 'The job is not answering a question. It is moving shared state forward.',
  },
  {
    id: 'why-openclaw',
    kicker: 'Why OpenClaw',
    title: 'A bounded proving ground',
    layout: 'trio',
    scene: scene(
      [1, 2, 7],
      [18, 14, 22],
      [112, 255, 90],
      [196, 52, 255],
      [255, 104, 44],
      { x: 0.86, y: 0.14, radius: 0.88, strength: 1.16 },
      {
        displayMode: 0.12,
        defense: 0.18,
        phase: 0.16,
        horizon: 0.58,
        bandCurve: 0.48,
        beamTilt: 0.64,
        lattice: 0.72,
        density: 0.52,
        aperture: 0.54,
        warningBias: 0.84,
        reticleBias: 0.28,
        scan: 0.6,
        notch: 0.36,
        skew: 0.14,
        contour: 0.62,
        interference: 0.46,
        pulse: 0.38,
        gate: 0.48,
      },
    ),
    cards: [
      { title: 'Dev flows', body: 'Test coding and internal operator patterns quickly.' },
      { title: 'Business flows', body: 'Try messy ops before locking product shape.', accent: 'focus' },
      { title: 'Client flows', body: 'Let real users expose the friction while risk stays bounded.', accent: 'cool' },
    ],
  },
  {
    id: 'primitive',
    kicker: 'Primitive',
    title: 'Disposable chats were the wrong unit',
    layout: 'split',
    scene: scene(
      [1, 3, 9],
      [28, 12, 42],
      [98, 238, 70],
      [218, 70, 255],
      [255, 96, 42],
      { x: 0.92, y: 0.12, radius: 0.86, strength: 1.34 },
      {
        displayMode: 0.88,
        defense: 0.28,
        phase: 0.12,
        horizon: 0.66,
        bandCurve: 0.42,
        beamTilt: 0.72,
        lattice: 0.66,
        density: 0.66,
        aperture: 0.46,
        warningBias: 0.9,
        reticleBias: 0.24,
        scan: 0.78,
        notch: 0.62,
        skew: 0.22,
        contour: 0.82,
        interference: 0.66,
        pulse: 0.56,
        gate: 0.6,
        sensorField: 0.94,
        bloom: 0.84,
        ruler: 0.92,
        diagnostics: 0.9,
        waist: 0.82,
      },
    ),
    panels: [
      {
        title: 'Old pattern',
        bullets: ['open chat', 'ask once', 'abandon thread', 'rebuild later'],
        accent: 'warm',
      },
      {
        title: 'Failure mode',
        body: 'Interrupted work keeps paying the reset cost.',
      },
    ],
  },
  {
    id: 'memory',
    kicker: 'Memory',
    title: 'Memory alone was still a patch',
    layout: 'split',
    scene: scene(
      [1, 3, 8],
      [32, 12, 50],
      [110, 236, 88],
      [236, 92, 255],
      [255, 114, 52],
      { x: 0.64, y: 0.1, radius: 0.84, strength: 1.24 },
      {
        displayMode: 0.9,
        defense: 0.22,
        phase: 0.22,
        horizon: 0.54,
        bandCurve: 0.5,
        beamTilt: 0.58,
        lattice: 0.64,
        density: 0.5,
        aperture: 0.52,
        warningBias: 0.82,
        reticleBias: 0.2,
        scan: 0.7,
        notch: 0.44,
        skew: 0.2,
        contour: 0.6,
        interference: 0.72,
        pulse: 0.46,
        gate: 0.42,
        sensorField: 0.88,
        bloom: 0.72,
        ruler: 0.86,
        diagnostics: 0.78,
        waist: 0.74,
      },
    ),
    panels: [
      {
        title: 'Useful for',
        bullets: ['preferences', 'recurring facts', 'basic business context'],
      },
      {
        title: 'Still missing',
        bullets: ['live working state', 'reliable continuity', 'clean handoff'],
        accent: 'warm',
      },
    ],
  },
  {
    id: 'shift',
    kicker: 'Shift',
    title: 'OpenClaw changes the unit of work',
    layout: 'trio',
    scene: scene(
      [1, 3, 9],
      [24, 10, 54],
      [84, 255, 88],
      [216, 68, 255],
      [255, 120, 50],
      { x: 0.42, y: 0.09, radius: 1.04, strength: 1.36 },
      {
        displayMode: 0.16,
        defense: 0.18,
        phase: 0.56,
        horizon: 0.46,
        bandCurve: 0.54,
        beamTilt: 0.56,
        lattice: 0.84,
        density: 0.58,
        aperture: 0.66,
        warningBias: 0.76,
        reticleBias: 0.16,
        scan: 0.62,
        notch: 0.52,
        skew: 0.16,
        contour: 0.78,
        interference: 0.58,
        pulse: 0.62,
        gate: 0.66,
      },
    ),
    cards: [
      { title: 'Continuity first', body: 'Persistent sessions matter more than another fresh thread.' },
      { title: 'Support second', body: 'Memory and compression support continuity.', accent: 'focus' },
      { title: 'Less reset', body: 'The work stays alive when humans pause.', accent: 'cool' },
    ],
  },
  {
    id: 'structure',
    kicker: 'Structure',
    title: 'One identity, many live contexts',
    layout: 'split-note',
    scene: scene(
      [1, 3, 8],
      [26, 12, 44],
      [92, 246, 84],
      [194, 54, 255],
      [255, 100, 40],
      { x: 0.8, y: 0.12, radius: 0.82, strength: 1.2 },
      {
        displayMode: 0.86,
        defense: 0.1,
        phase: 0.28,
        horizon: 0.6,
        bandCurve: 0.4,
        beamTilt: 0.6,
        lattice: 0.7,
        density: 0.48,
        aperture: 0.5,
        warningBias: 0.8,
        reticleBias: 0.3,
        scan: 0.56,
        notch: 0.4,
        skew: 0.18,
        contour: 0.52,
        interference: 0.42,
        pulse: 0.36,
        gate: 0.52,
        sensorField: 0.82,
        bloom: 0.38,
        ruler: 0.9,
        waist: 0.58,
      },
    ),
    panels: [
      { title: 'Shared substrate', bullets: ['identity', 'rules', 'memory'], accent: 'focus' },
      { title: 'Separate streams', bullets: ['distinct sessions', 'no accidental cross-talk', 'relay on purpose'] },
    ],
    note: 'Same assistant substrate. Separate live contexts. Intentional relay.',
  },
  {
    id: 'operations',
    kicker: 'Operations',
    title: 'Why operators care',
    layout: 'metrics',
    scene: scene(
      [1, 3, 8],
      [18, 12, 46],
      [102, 248, 76],
      [208, 60, 255],
      [255, 106, 44],
      { x: 0.54, y: 0.08, radius: 0.98, strength: 1.38 },
      {
        displayMode: 0.56,
        defense: 0.96,
        phase: 0.48,
        horizon: 0.64,
        bandCurve: 0.62,
        beamTilt: 0.58,
        lattice: 0.9,
        density: 0.76,
        aperture: 0.56,
        warningBias: 0.78,
        reticleBias: 0.36,
        scan: 0.74,
        notch: 0.58,
        skew: 0.14,
        contour: 0.86,
        interference: 0.5,
        pulse: 0.52,
        gate: 0.74,
        sensorField: 0.14,
        bloom: 0.46,
        ruler: 0.2,
        diagnostics: 0.34,
        waist: 0.44,
      },
    ),
    metrics: [
      { label: 'Long work', body: 'Pause and resume cleanly.' },
      { label: 'Multiple humans', body: 'Share one assistant identity.' },
      { label: 'Isolation', body: 'Contain cross-talk.' },
      { label: 'Background jobs', body: 'Keep work moving between messages.' },
    ],
  },
  {
    id: 'today',
    kicker: 'Today',
    title: 'Claws in practice',
    layout: 'names',
    scene: scene(
      [1, 3, 8],
      [34, 12, 48],
      [112, 236, 94],
      [228, 88, 255],
      [255, 120, 54],
      { x: 0.86, y: 0.12, radius: 0.86, strength: 1.24 },
      {
        displayMode: 0.88,
        defense: 0.24,
        phase: 0.18,
        horizon: 0.58,
        bandCurve: 0.46,
        beamTilt: 0.64,
        lattice: 0.68,
        density: 0.52,
        aperture: 0.6,
        warningBias: 0.84,
        reticleBias: 0.34,
        scan: 0.64,
        notch: 0.46,
        skew: 0.2,
        contour: 0.64,
        interference: 0.56,
        pulse: 0.44,
        gate: 0.5,
        sensorField: 0.52,
        bloom: 0.56,
        ruler: 0.46,
        diagnostics: 0.42,
        waist: 0.58,
      },
    ),
    names: ['Ali', 'Fraser', 'Kylie', 'Monica'],
    panels: [
      {
        title: 'What that implies',
        bullets: ['distinct roles', 'real team usage', 'shared platform, different boundaries'],
        accent: 'focus',
      },
    ],
  },
  {
    id: 'ali',
    kicker: 'Example',
    title: 'Ali is a legible claw',
    layout: 'split',
    scene: scene(
      [1, 3, 8],
      [30, 14, 44],
      [92, 248, 86],
      [196, 50, 255],
      [255, 92, 44],
      { x: 0.66, y: 0.1, radius: 0.94, strength: 1.32 },
      {
        displayMode: 0.82,
        defense: 0.16,
        phase: 0.26,
        horizon: 0.62,
        bandCurve: 0.48,
        beamTilt: 0.6,
        lattice: 0.74,
        density: 0.58,
        aperture: 0.54,
        warningBias: 0.8,
        reticleBias: 0.24,
        scan: 0.68,
        notch: 0.54,
        skew: 0.18,
        contour: 0.72,
        interference: 0.48,
        pulse: 0.48,
        gate: 0.58,
      },
    ),
    panels: [
      { title: 'Role', bullets: ['calendar context', 'scheduling', 'follow-through'] },
      { title: 'Why it lands', body: 'Everyone understands an executive assistant, so the value reads fast.', accent: 'cool' },
    ],
  },
  {
    id: 'priorities',
    kicker: 'V1',
    title: 'Current claw priorities',
    layout: 'grid',
    scene: scene(
      [1, 3, 8],
      [28, 12, 42],
      [96, 240, 80],
      [214, 72, 255],
      [255, 104, 46],
      { x: 0.74, y: 0.1, radius: 0.96, strength: 1.32 },
      {
        displayMode: 0.3,
        defense: 0.18,
        phase: 0.14,
        horizon: 0.68,
        bandCurve: 0.52,
        beamTilt: 0.62,
        lattice: 0.8,
        density: 0.64,
        aperture: 0.58,
        warningBias: 0.82,
        reticleBias: 0.28,
        scan: 0.72,
        notch: 0.48,
        skew: 0.16,
        contour: 0.76,
        interference: 0.54,
        pulse: 0.5,
        gate: 0.64,
      },
    ),
    cards: [
      { title: 'Continuity', body: 'Persistent sessions over disposable prompts.' },
      { title: 'Boundaries', body: 'Clear permissions, limits, and escalation.' },
      { title: 'Relay', body: 'Intentional handoff across people and surfaces.' },
      { title: 'Usability', body: 'Operational value over novelty.' },
    ],
  },
  {
    id: 'target',
    kicker: 'Target',
    title: 'What a good claw gives you',
    layout: 'closing',
    scene: scene(
      [1, 2, 6],
      [16, 12, 18],
      [116, 255, 88],
      [210, 54, 255],
      [255, 116, 48],
      { x: 0.84, y: 0.08, radius: 1.08, strength: 1.48 },
      {
        displayMode: 0.54,
        defense: 0.4,
        phase: 0.1,
        horizon: 0.72,
        bandCurve: 0.7,
        beamTilt: 0.66,
        lattice: 0.92,
        density: 0.8,
        aperture: 0.72,
        warningBias: 0.88,
        reticleBias: 0.18,
        scan: 0.8,
        notch: 0.56,
        skew: 0.12,
        contour: 0.9,
        interference: 0.6,
        pulse: 0.66,
        gate: 0.78,
        sensorField: 0.36,
        bloom: 0.5,
        ruler: 0.24,
        diagnostics: 0.22,
        waist: 0.52,
      },
    ),
    cards: [
      { title: 'Continuity', body: 'Work survives interruption.' },
      { title: 'Bounded action', body: 'Roles, permissions, and deliberate relay.', accent: 'focus' },
      { title: 'Operational value', body: 'Background execution and fast learning in real systems.', accent: 'cool' },
    ],
    closing: 'The useful future is not one giant chatbot. It is claws inside real business systems.',
  },
];
